/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AreaDatiRouteImport } from './routes/area-dati'
import { Route as IndexRouteImport } from './routes/index'

const AreaDatiRoute = AreaDatiRouteImport.update({
  id: '/area-dati',
  path: '/area-dati',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-dati': typeof AreaDatiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-dati': typeof AreaDatiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-dati': typeof AreaDatiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/area-dati'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/area-dati'
  id: '__root__' | '/' | '/area-dati'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaDatiRoute: typeof AreaDatiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/area-dati': {
      id: '/area-dati'
      path: '/area-dati'
      fullPath: '/area-dati'
      preLoaderRoute: typeof AreaDatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaDatiRoute: AreaDatiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
